import { ILeaderboardData } from '@/types/index';

export const mokeLeaderboardData: ILeaderboardData[] = [
  {
    rank: 1,
    userName: 'UserName1',
    userIcon: '/asserts/emptyUserIcon.svg',
    points: 2234345,
    lvl: 40,
    activeReferrals: 10,
    maxSteak: 123,
  },
  {
    rank: 2,
    userName: 'UserName2',
    userIcon: '/asserts/emptyUserIcon.svg',
    points: 1234345,
    lvl: 35,
    activeReferrals: 10,
    maxSteak: 109,
  },
  {
    rank: 3,
    userName: 'UserName3',
    userIcon: '/asserts/emptyUserIcon.svg',
    points: 934345,
    lvl: 30,
    activeReferrals: 98,
    maxSteak: 0,
  },
  {
    rank: 4,
    userName: 'UserName4',
    userIcon: '/asserts/emptyUserIcon.svg',
    points: 834345,
    lvl: 28,
    activeReferrals: 99,
    maxSteak: 0,
  },
  {
    rank: 5,
    userName: 'UserName5',
    userIcon: '/asserts/emptyUserIcon.svg',
    points: 834345,
    lvl: 28,
    activeReferrals: 102,
    maxSteak: 0,
  },
  {
    rank: 6,
    userName: 'UserName6',
    userIcon: '/asserts/emptyUserIcon.svg',
    points: 734345,
    lvl: 25,
    activeReferrals: 55,
    maxSteak: 0,
  },
  {
    rank: 7,
    userName: 'UserName7',
    userIcon: '/asserts/emptyUserIcon.svg',
    points: 634345,
    lvl: 23,
    activeReferrals: 32,
    maxSteak: 0,
  },
  {
    rank: 8,
    userName: 'UserName8',
    userIcon: '/asserts/emptyUserIcon.svg',
    points: 0,
    lvl: 0,
    activeReferrals: 10,
    maxSteak: 123,
  },
  {
    rank: 9,
    userName: 'UserName9',
    userIcon: '/asserts/emptyUserIcon.svg',
    points: 0,
    lvl: 0,
    activeReferrals: 10,
    maxSteak: 109,
  },
  {
    rank: 10,
    userName: 'UserName10',
    userIcon: '/asserts/emptyUserIcon.svg',
    points: 0,
    lvl: 0,
    activeReferrals: 98,
    maxSteak: 0,
  },
  {
    rank: 11,
    userName: 'UserName11',
    userIcon: '/asserts/emptyUserIcon.svg',
    points: 0,
    lvl: 0,
    activeReferrals: 99,
    maxSteak: 0,
  },
  {
    rank: 12,
    userName: 'UserName12',
    userIcon: '/asserts/emptyUserIcon.svg',
    points: 0,
    lvl: 0,
    activeReferrals: 102,
    maxSteak: 0,
  },
  {
    rank: 13,
    userName: 'UserName6',
    userIcon: '/asserts/emptyUserIcon.svg',
    points: 0,
    lvl: 0,
    activeReferrals: 0,
    maxSteak: 0,
  },
  {
    rank: 14,
    userName: 'UserName14',
    userIcon: '/asserts/emptyUserIcon.svg',
    points: 0,
    lvl: 0,
    activeReferrals: 32,
    maxSteak: 0,
  },
];
