import { IAchievementCard } from '@/types/index';

export const mokeAchievements: IAchievementCard[] = [
  {
    currency: '$',
    amount: 30000,
    pointsAmount: 8,
    maxAmount: 100000,
    maxPoints: 20,
    description: 'Amount on balance',
  },
  {
    currency: '$',
    amount: 75000,
    pointsAmount: 16,
    maxAmount: 100000,
    maxPoints: 20,
    description: 'Transaction volume',
  },
  {
    currency: '',
    amount: 5,
    pointsAmount: 1,
    maxAmount: 100000,
    maxPoints: 20,
    description: 'Transactions with contracts',
  },
  {
    currency: '',
    amount: 0,
    pointsAmount: 1,
    maxAmount: 100000,
    maxPoints: 20,
    description: 'Wallet transactions',
  },
  {
    currency: 'day',
    amount: 5,
    pointsAmount: 1,
    maxAmount: 100,
    maxPoints: 20,
    description: 'Transactions on days',
  },
  {
    currency: 'week',
    amount: 1,
    pointsAmount: 1,
    maxAmount: 20,
    maxPoints: 20,
    description: 'Transactions of weeks',
  },
  {
    currency: 'month',
    amount: 0,
    pointsAmount: 1,
    maxAmount: 10,
    maxPoints: 20,
    description: 'Transactions of months',
  },
  {
    currency: '',
    amount: 5,
    pointsAmount: 1,
    maxAmount: 100000,
    maxPoints: 20,
    description: 'Gas Spended',
  },
];
